### ISSUE TITLE
BsbGateway - serial port + Web Interface

### ISSUE THREAD

**Issue by fred-c1** [loehnertj/bsbgateway#15]
Hello Johannes,

I am planning to try our software on a Raspberry pi 3B+
Can I use a serial port (UART) connected to a USB port?
If you have some time, I think it would help to add a (some?) screenshot of the web interface in order to understand the capabilities.

Thanks,
Fred

**Comment by fred-c1** [comment]
OK: I was looking in bsb_comm.py      (1st time I see a Python file...)
Looking at config.py everything is now clear.
Just 1 question regarding avoiding collision (by monitoring CTS signal of the serial port):
How critical is this? Strongly recommended?
My main concern would be corrupting the parameters of my heat pump. Is there a risk?

**Comment by loehnertj** [comment]
Not critical at all probably. In the discussions that I read so far, nobody else seemed to care about collision avoidance. I am not even sure how well it actually works (not owning a logic analyzer...) I think the worst that could happen is that messages get lost every now and then.

**Comment by strubbi77** [comment]
Hi, do you think it possible to use
https://adapter.ebusd.eu/index.en.html together with your Code? 
Difference is 2400 Baud vs. 4800 Baud.  And logical 1 and 0 are different. 

Best regards Thomas

**Comment by loehnertj** [comment]
Hi Thomas, depends on what you want to do exactly.

A. Connecting to an eBUS device (what the adapter is intended for) - 100% no. eBUS and BSB are two different "languages" and bsbgateway definitely does not understand the eBUS protocol.

B. Out-of-spec use to connect to a BSB device: 50% no.
* Voltage levels and electrical sending part *might* actually work, from what I read from the circuit schematic
* Baud rate 4800, parity and stop bit must match exactly to the BSB specs. I don't know any of the ICs used in the circuit, so this may be the showstopper, if the board does its own digital processing.
* I didn't check how eBUS peers are supposed to handle collisions compared to BSB. But I would guess that one could get away with just ignoring the problem.
* Lastly, the RPi interface of your board seems to communicate via SPI. bsbgateway currently only has a driver for standard RS232 (serial) interfaces. SPI communication is possible in RPi/python, but somebody :-) would have to program a driver module for it analogous to ``serial_source.py``.

If "B" is what you're aiming for, the developer(s) of the board should be able to answer those questions with much more certainty than me.

**Comment by strubbi77** [comment]
Thanks for your input. 
It would be B, so the Out-of-Spec usage of the eBUS <-> USB device. (Or at least the base design.)
Modifying the code or writing the USB-driver would be easier for me than building the board for the communication from scratch. So for me it's a point of which aproach (<60€) brings me to the goal with the highest success rate.
