### ISSUE TITLE
Missing response hangs Web interface forever

### ISSUE THREAD

**Issue by loehnertj** [loehnertj/bsbgateway#19]
There should be a timeout and/or correct error response when a field value cannot be retrieved in due time.

Taken over from #18:

I still have some issues related with requests which are not getting a response. For me, the pre-configured key 5970 (part of group-0) is such a case.
A request to this key never gets a response. There is also no timeout handling.

When I then try to leave bsbgateway using "quit", after such an (unresponded) request, the process does not exit. Only after using multiple Ctrl+C, the final event source stops ("event source hub ").

INFO bsbgateway.web_interface:144 @36281 -- 192.168.2.51:23047: GET /field-1010.widget - 200 OK
INFO bsbgateway.web_interface:144 @36785 -- 192.168.2.51:23047: GET /field-658.widget - 200 OK
quit
DEBUG bsbgateway.event_sources:105 @47829 -- event source  will stop somewhen...
DEBUG bsbgateway.event_sources:105 @47830 -- event source  will stop somewhen...
DEBUG bsbgateway.event_sources:93 @47837 -- event source web exited.
DEBUG bsbgateway.event_sources:93 @48132 -- event source timer exited.
^C^C^C^C^C^CDEBUG bsbgateway.event_sources:93 @51800 -- event source hub exited.

Looks like

    There is no timeout handling for requests without a response (from the heating?)
    Unresponded requests sitting in some processing queue prevent bsbgateway from a clean exit using "quit".

This will not be a problem for the intended productive use-case. Not important.

**Comment by Lamarqe** [comment]
This problem is also fixed with one of the most recent commits, most likely https://github.com/loehnertj/bsbgateway/commit/8ea0082dd2cda3ffb3695c517f631fbcb910b59d.
