### ISSUE TITLE
Error in http Request/Response handling, e.g. in case of CRC checksum errors

### ISSUE THREAD

**Issue by Lamarqe** [loehnertj/bsbgateway#20]
Test scenario: Cyclically send a request every 60 seconds (or any other frequncy) via the web interface.
Eg http GET request for field-8830.value.

This runs perfectly fine for hours until there appears a slight communication error, which causes a CRC error:
```
Jan 16 00:21:03 keller config.py[15924]: INFO bsbgateway.bsb.bsb_comm:115 @4395897 -- ++++b'\xdc\x8a\x00\x0b\x06=\xbd\x99\x00\x0b\x06=1\x05/\\' :: bad crc checksum for: DC 8A 00 0B 06 3D BD 99 00 0B 06
Jan 16 00:21:03 keller config.py[15924]: INFO bsbgateway.bsb.bsb_comm:115 @4395905 -- ++++b'\xdc\x8a\x00\x0b\x06=\xbd\x99\x00\x0b\x06=1\x05/\\\x1c' :: bad crc checksum for: DC 8A 00 0B 06 3D BD 99 00 0B 06
Jan 16 00:21:03 keller config.py[15924]: INFO bsbgateway.bsb.bsb_comm:115 @4396029 -- ++++b'\xdc\x8a\x00\x0b\x06=\xbd\x99\x00\x0b\x06=1\x05/\\\x1c' :: bad crc checksum for: DC 8A 00 0B 06 3D BD 99 00 0B 06
```

Interestingly, this error message is reported multiple times for the same timestamp even though there was just a single http request in this second.

After this situation happened, there is a a persistent error in the request/response mapping, specifically for the request field-8830.value:
(Requests for other values are not affected and properly receive respones)

Requests no longer receive a "direct" response afterwards. In case of home assistant the observable behavior is that every request times out afterwards:
```
2023-01-16 00:21:13.334 ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: http://127.0.0.1:8081/field-8830.value
2023-01-16 00:22:23.329 ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: http://127.0.0.1:8081/field-8830.value
2023-01-16 00:23:33.329 ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: http://127.0.0.1:8081/field-8830.value
2023-01-16 00:24:43.326 ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: http://127.0.0.1:8081/field-8830.value
```
...and so on

Using manual requests from the command line I found out that the problem is caused by a request/response mismatch.

1. When I first request the field-8830 after this initial error situation from a command line, the request also just hangs.
2. When I then request the field-8830 again from a 2nd command line shell, the request in the first shell receives the response! Now the 2nd shell hangs.
3. When I then request the field-8830 again from the 1st command line shell, the 2nd shell receives the response and the request in the 1st shell hangs again. 
4. And so on....

In contrast to https://github.com/loehnertj/bsbgateway/issues/19 , this problem is important, as it prevents the productive use because communication fails entirely for this field right after the first CRC communication error on the BSB bus.

**Comment by Lamarqe** [comment]
I have to correct myself.
The poblem of wrongly mapped request/response handling occurs even without crc checksum errors:

Eg:
```
Jan 16 22:28:48 keller config.py[36241]: INFO bsbgateway.web_interface:144 @2161483 -- 127.0.0.1:60644: GET /field-8830.value - 200 OK
Jan 16 22:29:48 keller config.py[36241]: INFO bsbgateway.web_interface:144 @2221491 -- 127.0.0.1:34320: GET /field-8830.value - 200 OK
Jan 16 22:31:58 keller config.py[36241]: INFO bsbgateway.web_interface:144 @2351468 -- 127.0.0.1:57798: GET /field-8830.value - 200 OK
Jan 16 22:33:08 keller config.py[36241]: INFO bsbgateway.web_interface:144 @2421488 -- 127.0.0.1:37344: GET /field-8830.value - 200 OK
Jan 16 22:34:18 keller config.py[36241]: INFO bsbgateway.web_interface:144 @2491483 -- 127.0.0.1:54362: GET /field-8830.value - 200 OK
Jan 16 22:35:28 keller config.py[36241]: INFO bsbgateway.web_interface:144 @2561483 -- 127.0.0.1:58034: GET /field-8830.value - 200 OK
```

Notice the missing response at 22:30:48. Afterwards requests&responses do no longer match and clients no longer get a direct response. Home assistant (correctly) starts to time out at this point:

```
2023-01-16 22:30:58.344 ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: http://127.0.0.1:8081/field-8830.value
2023-01-16 22:32:08.319 ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: http://127.0.0.1:8081/field-8830.value
2023-01-16 22:33:18.325 ERROR (MainThread) [homeassistant.components.rest.data] Timeout while fetching data: http://127.0.0.1:8081/field-8830.value
```

**Comment by loehnertj** [comment]
Found likely cause and pushed fix. Please try if the problem is fixed, reopen if not.

There is still the problem that requests are not properly serialized and rate-limited, will look at this in the next days.

**Comment by Lamarqe** [comment]
Yes, the commit seems to do the trick. 
Now the request handling recovers from a communication glitch:

```
Jan 17 21:30:29 keller config.py[56508]: INFO bsbgateway.web_interface:144 @2661700 -- 127.0.0.1:35482: GET /field-8830.value - 200 OK
Jan 17 21:31:29 keller config.py[56508]: INFO bsbgateway.bsb.bsb_comm:115 @2721611 -- ++++b'\xdc\x8a\x00\x0b\xbbI\x0b\x06=1\x05/\\\x1c' :: bad crc checksum for: DC 8A 00 0B BB 49 0B 06 3D 31 05
Jan 17 21:31:29 keller config.py[56508]: INFO bsbgateway.bsb.bsb_comm:115 @2721718 -- ++++b'\xdc\x8a\x00\x0b\xbbI\x0b\x06=1\x05/\\\x1c' :: bad crc checksum for: DC 8A 00 0B BB 49 0B 06 3D 31 05
Jan 17 21:31:32 keller config.py[56508]: ERROR bsbgateway.web_interface.field:88 @2724579 -- error while requesting value: TimeoutError: No response from BSB device
Jan 17 21:31:32 keller config.py[56508]: INFO bsbgateway.web_interface:144 @2724579 -- 127.0.0.1:56408: GET /field-8830.value - 500
Jan 17 21:32:32 keller config.py[56508]: INFO bsbgateway.web_interface:144 @2784699 -- 127.0.0.1:58408: GET /field-8830.value - 200 OK

```
Thank you!
