### ISSUE TITLE
I have to add delay for loggers 

### ISSUE THREAD

**Issue by Leonleon33** [loehnertj/bsbgateway#21]
Without time.sleep(xx.yy) only the first 'logger' in "loggers" is written in the file <tracefile_dir>/<disp_id>.trace 
With modification in bsb_gateway.py line 92, all loggers are written.
    def on_timer_event(o, data):
        if int(time.time()) % o.atomic_interval!=0:
            return
        for logger in o.loggers:
            logger.tick()
            # add time.sleep(.25) #
            time.sleep(.29) # .25 insuffisant

**Comment by loehnertj** [comment]
Probably fixed by f283040e037557294375cd0488ef7dbea4e95b95. Please check and reopen if not.
Note the new config variable ``min_wait_s`` (default 0.1s)

**Comment by Leonleon33** [comment]
Ok with min_wait_s at 0.2s (0.1 not enough ; tried 0.15, not enough)

**Comment by retogaeh** [comment]
Hey there, interesting. I recently got to know your bsbgateway while preparing for a heat pump logger of a future heating system. This was one section in the code I was wondering how it will be managed by the controller if it gets flooded with requests. Sounds like it is not capable of stacking them up but rather wants to respond before accepting a new request. I would assume that in the mentioned 150 to 200 ms a respond was received. Is that the case? 

If that is true, why not syncing the writer and reader of the serial interface and only allowing an addressed request once the previous one has been answered?

**Comment by Lamarqe** [comment]
Why would you optimize on this behavior.

Because its possible? Okay, might be.
Because you want to run a massive load test on your boiler? There easier ways to damage your heating. 

I don't see a use-case. The way how bsbgateway works right now fullfills all use-cases I currently see.

**Comment by Leonleon33** [comment]
I am using bsbgateway to control and log infos from my heat pump since 2017 (Siemens RVS61 controler)
(Heat pump -- serial hardware -- Esp32 running serial over wifi -- Ubuntu 22.04 computer running bsbgateway , netcat , tty0tty)

Having to delay between request do not appear for me as problematic.
Bsbgateway does the job I want
The ubuntu computer verify every 5 mn if it can get a temperature reading ; if not it restarts bsbgateway and netcat. (very seldom)
Cron jobs to change some temperature parameters

I want to thank Johannes Löhnert for his work.

**Comment by loehnertj** [comment]
@retogaeh : The wait time is on one hand to give other peers on the bus a chance to send, and on the other hand to have a strong *chance* to get the reply before sending the next request. But the latter is by no means ensured or assumed.

As it is currently, requests can stack up in the queue infinitely, if requests come too frequently. Thinking of it, I'll add a limit for the number of pending requests.

**Comment by loehnertj** [comment]
Limit added in  e394978ac1a7b2557884154f3807990ddbcb2a50
