### ISSUE TITLE
bad crc checksum

### ISSUE THREAD

**Issue by ferllings** [loehnertj/bsbgateway#23]
Hello,

I have the following CRC error (in loop) when I launch bsbgateway:
```
INFO bsbgateway.bsb.bsb_comm:127 @17951 -- ++++b'\xdc\x80\x17\x0e\x07I=\x05\xee\xbd\x05\x0b\x06=\x05\x07' :: bad crc checksum for: DC 80 17 0E 07 49 3D 05 EE BD 05 0B 06 3D
INFO bsbgateway.bsb.bsb_comm:127 @17965 -- ++++b'\xdc\x80\x17\x0e\x07I=\x05\xee\xbd\x05\x0b\x06=\x05\x07\xae<\xa3' :: bad crc checksum for: DC 80 17 0E 07 49 3D 05 EE BD 05 0B 06 3D
```

Note that it doesn't seems to affect the other results.

**Comment by loehnertj** [comment]
Hm, all that I can say is that the checksum in the printed data is indeed wrong. What kind of device are you connected to? Do you get no data at all, or is this just an annoyance inbetween?

Checksum is the last two bytes of the b-string: `\x05\x07` i.e. `0x0507`. If you check with an [Online Calculator](https://www.lammertbies.nl/comm/info/crc-calculation), correct checksum would be `0x98EA` (CRC-CCITT / XModem).

So it may be that your device's checksum algorithm is buggy. Another possibility might be that the length field (4th byte `0x0E` = 14 bytes) is wrong - this is indicated by the second message, normally the next telegram should begin with `0xDC` again, but actually the following bytes were `0xAE3CA3`. Or there is some variability in the protocol that I don't know about (this was all reverse-engineered).

You can try patching out the CRC Check in [bsb_telegram.py:117](https://github.com/loehnertj/bsbgateway/blob/1ba455cb83c022edc6a7ba70a34db37a643fbc2b/bsbgateway/bsb/bsb_telegram.py#L117). However my gut feeling is that this won't help.
